#! /usr/bin/env bash

set -x

if ! command -v zig > /dev/null; then
  echo "Error: zig is not on the PATH. Install zig and make sure it's on PATH. Follow instructions at https://github.com/fallenwood/PublishAotCross"
  exit 1
fi

args="$*"

# Works around zlib not being available with zig. This is not great.
args=${args//-lz /}

# Work around a .NET 8 Preview 6 issue
args=${args//-Wl,-rpath,\$ORIGIN/-Wl,-rpath,\$ORIGIN}

# Work around parameters unsupported by zig. Just drop them from the command line.
args=${args//--discard-all/--as-needed}
args=${args//-Wl,-pie /}
args=${args//-pie /}
args=${args//-Wl,-e0x0 /}

# Works around zig linker dropping necessary parts of the executable.
read -ra arr <<< "$args"
arr=("${arr[@]:0:3}" "-Wl,-u,__Module" "${arr[@]:3}")
args="${arr[*]}"


# Run zig cc
zig cc "${arr[@]}"
