name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to create'
        required: false

jobs:
  build_multitarget_linux:
    strategy:
      matrix:
        include:
          - vm: ubuntu-24.04
    runs-on: ${{ matrix.vm }}
    name: Build Multi Target ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'
      - name: Install lld-link
        run: sudo apt-get install --no-install-suggests --no-install-recommends lld llvm

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Setup xwin
        run: |
          xwin_version="0.6.6-rc.2"
          wget https://github.com/Jake-Shadle/xwin/releases/download/${xwin_version}/xwin-${xwin_version}-x86_64-unknown-linux-musl.tar.gz
          tar -xf xwin-${xwin_version}-x86_64-unknown-linux-musl.tar.gz
          mkdir -p $HOME/.local/bin
          cp xwin-${xwin_version}-x86_64-unknown-linux-musl/xwin $HOME/.local/bin
          chmod +x $HOME/.local/bin/xwin
      - name: Build (CI)
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj
          dotnet publish -r linux-musl-arm64 -c Release test/Hello.csproj -p:StripSymbols=true
          dotnet publish -r linux-musl-x64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-musl-arm -c Release test/Hello9.csproj -p:StripSymbols=true -o output-linux-musl-arm
          dotnet publish -r win-x64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-win-x64
          dotnet publish -r win-x64 -c Release test/Hello9.csproj -p:StripSymbols=true -o output-win-x64
          dotnet publish -r win-arm64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-win-arm64
          dotnet publish -r win-arm64 -c Release test/Hello9.csproj -p:StripSymbols=true -o output-win-arm64

  build_multitarget_windows:
    strategy:
      matrix:
        include:
          - vm: windows-latest
    runs-on: ${{ matrix.vm }}
    name: Build Multi Target ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Build (CI)
        run: |
          dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj
          dotnet publish -r linux-musl-arm64 -c Release test/Hello.csproj -p:StripSymbols=true
          dotnet publish -r linux-musl-x64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-musl-arm -c Release test/Hello9.csproj -p:StripSymbols=true -o output-linux-musl-arm

  build_multitarget_macos:
    strategy:
      matrix:
        include:
          - vm: macos-latest
    runs-on: ${{ matrix.vm }}
    name: Build Multi Target ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20.1.0"

      - name: Build (CI)
        run: |
          dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj
          dotnet publish -r linux-musl-arm64 -c Release test/Hello.csproj -p:StripSymbols=true
          dotnet publish -r linux-musl-x64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-musl-arm -c Release test/Hello9.csproj -p:StripSymbols=true -o output-linux-musl-arm

  build:
    strategy:
      matrix:
        include:
          - vm: windows-latest
    runs-on: ${{ matrix.vm }}
    name: Build and Validate ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "0.15.1"

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Build (CI)
        run: |
          dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj
          dotnet publish -r linux-x64 -c Release test/Hello.csproj -p:StripSymbols=true -p:UseExternalZig=true
      - name: Upload test binary
        uses: actions/upload-artifact@v4
        with:
          name: Hello
          path: test/bin/Release/net8.0/linux-x64/publish/Hello

  validate:
    needs: build
    runs-on: ubuntu-latest
    name: Try launching
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: Hello
      - name: Launch
        run: |
          chmod +x ./Hello
          ./Hello

  release:
    needs: [validate, build_multitarget_linux, build_multitarget_windows, build_multitarget_macos]
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: latest
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - uses: milliewalky/setup-7-zip@v2
        with:
          tag: "latest"

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Build (CD)
        if: ${{ github.event.inputs.version != '' }}
        run: dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj -p:Version=${{ github.event.inputs.version }}
      - name: Push to GitHub package registry
        if: ${{ github.event.inputs.version != '' }}
        run: dotnet nuget push src/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      - name: Push to NuGet.org
        if: ${{ github.event.inputs.version != '' }}
        run: dotnet nuget push src/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
