name: PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build_multitarget_linux:
    strategy:
      matrix:
        include:
          - vm: ubuntu-26.04
    runs-on: ${{ matrix.vm }}
    name: Build Multi Target ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'
      - name: Setup dotnet 10.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '10.0.x'
      - name: Setup dotnet 11.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '11.0.x'
          include-prerelease: true
      - name: Install llvm
        run: sudo apt-get install --no-install-suggests --no-install-recommends llvm

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "0.16.0"

      - name: Setup xwin
        run: |
          xwin_version="0.9.0"
          wget https://github.com/Jake-Shadle/xwin/releases/download/${xwin_version}/xwin-${xwin_version}-x86_64-unknown-linux-musl.tar.gz
          tar -xf xwin-${xwin_version}-x86_64-unknown-linux-musl.tar.gz
          mkdir -p $HOME/.local/bin
          cp xwin-${xwin_version}-x86_64-unknown-linux-musl/xwin $HOME/.local/bin
          chmod +x $HOME/.local/bin/xwin
      - name: Build (CI)
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          pwsh ./nuget_pack.ps1
          dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj
          dotnet publish -r linux-musl-arm64 -c Release test/Hello.csproj -p:StripSymbols=true
          dotnet publish -r linux-musl-x64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-musl-arm -c Release test/Hello9.csproj -p:StripSymbols=true -o output-linux-musl-arm
          dotnet publish -r linux-musl-arm -c Release test/Hello10.csproj -p:StripSymbols=true -o output-linux-musl-arm
          dotnet publish -r win-x64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-win-x64
          dotnet publish -r win-x64 -c Release test/Hello9.csproj -p:StripSymbols=true -o output-win-x64
          dotnet publish -r win-x64 -c Release test/Hello10.csproj -p:StripSymbols=true -o output-win-x64
          dotnet publish -r win-arm64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-win-arm64
          dotnet publish -r win-arm64 -c Release test/Hello9.csproj -p:StripSymbols=true -o output-win-arm64
          dotnet publish -r win-arm64 -c Release test/Hello10.csproj -p:StripSymbols=true -o output-win-arm64
          dotnet publish -r linux-x64 -c Release test/TestNupkg.csproj -p:StripSymbols=true -o output-testnuget-linux-x64
          dotnet publish -r linux-arm64 -c Release test/TestNupkg.csproj -p:StripSymbols=true -o output-testnuget-linux-arm64

  build_multitarget_windows:
    strategy:
      matrix:
        include:
          - vm: windows-latest
    runs-on: ${{ matrix.vm }}
    name: Build Multi Target ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'
      - name: Setup dotnet 10.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Build (CI)
        run: |
          pwsh ./nuget_pack.ps1
          dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj
          dotnet publish -r linux-musl-arm64 -c Release test/Hello.csproj -p:StripSymbols=true
          dotnet publish -r linux-musl-x64 -c Release test/Hello.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-musl-arm -c Release test/Hello9.csproj -p:StripSymbols=true -o output-linux-musl-arm
          dotnet publish -r linux-musl-x64 -c Release test/Hello10.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-musl-x64 -c Release test/HelloStatic8.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-musl-x64 -c Release test/HelloStatic10.csproj -p:StripSymbols=true -o output-linux-musl-x64
          dotnet publish -r linux-x64 -c Release test/TestNupkg.csproj -p:StripSymbols=true -o output-testnuget-linux-x64
          dotnet publish -r linux-arm64 -c Release test/TestNupkg.csproj -p:StripSymbols=true -o output-testnuget-linux-arm64

  build:
    strategy:
      matrix:
        include:
          - vm: windows-latest
    runs-on: ${{ matrix.vm }}
    name: Build and Validate ${{ matrix.vm }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "0.16.0"

      - name: Download llvm-objcopy
        run: ./src/download-llvm-objcopy.ps1
        shell: pwsh

      - name: Build (CI)
        run: |
          pwsh ./nuget_pack.ps1
          dotnet build -c Release -t:Pack src/Fallenwood.PublishAotCross.nuproj
          dotnet publish -r linux-x64 -c Release test/Hello.csproj -p:StripSymbols=true -p:UseExternalZig=true
      - name: Upload test binary
        uses: actions/upload-artifact@v4
        with:
          name: Hello
          path: test/bin/Release/net8.0/linux-x64/publish/Hello

  validate:
    needs: build
    runs-on: ubuntu-latest
    name: Try launching
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: Hello
      - name: Launch
        run: |
          chmod +x ./Hello
          ./Hello
